kind: Service
apiVersion: v1
metadata:
  name: server-service
  labels:
    app: wishu-server
    tier: backend
spec:
  selector:
    app: wishu-server
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
