apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data-pvc
  labels:
    app: wishu-server
    tier: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  labels:
    app: wishu-server
    tier: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi