apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  labels:
    app: nextcloud
data:
  NEXTCLOUD_UPDATE: '1'
  ALLOW_EMPTY_PASSWORD: 'yes'
  POSTGRES_HOST: 'postgres-service'
  POSTGRES_DB: 'nextcloud'
  NEXTCLOUD_ADMIN_USER: 'nextcloud_admin'
  NEXTCLOUD_ADMIN_PASSWORD: 'nextcloud_admin_password'
