FROM ubuntu:latest

ENV ENV=${ENV} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/src/ 
    
RUN apt-get update && apt-get install -y \
    python3-pip 

COPY ./requirements.txt /

RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

ADD ./src /src

WORKDIR /src

VOLUME [.]

ENTRYPOINT ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
